version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
